**Импортировать NumPy под именем np**

In [1]:
import numpy as np

**Напечатать версию и конфигурацию**

In [2]:
print(np.__version__)

1.21.2


**Создать вектор (одномерный массив) размера 10, заполненный нулями**

In [3]:
np_array = np.zeros(10)
print(np_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Создать вектор размера 10, заполненный единицами**

In [4]:
np_array = np.ones(10)
print(np_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


**Создать вектор размера 10, заполненный числом 2.5**

In [5]:
np_array = np.full(10, 2.5)
print(np_array)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


**Как получить документацию о функции numpy.add из командной строки?**

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

**Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1**

In [7]:
np_array = np.zeros(10)
np_array[4] = 1
print(np_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**Создать вектор со значениями от 10 до 49**

In [8]:
np_array = np.arange(10, 50)
print(np_array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**Развернуть вектор (первый становится последним)**

In [9]:
np_array = np.arange(10)
print(np_array)

np_array = np_array[::-1]
print(np_array)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


**Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8**

In [10]:
np_array = np.arange(9).reshape(3, 3)
print(np_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Найти индексы ненулевых элементов в [1, 2, 0, 0, 4, 0]**

In [11]:
np_array = np.array([1, 2, 0, 0, 4, 0])
print(np_array.nonzero())

(array([0, 1, 4], dtype=int64),)


**Создать массив 3x3x3 со случайными значениями**

In [12]:
np_array = np.random.rand(3, 3, 3)
print(np_array)

[[[0.65238138 0.6093055  0.12478065]
  [0.38947046 0.04516058 0.46258648]
  [0.60990118 0.81063977 0.34352228]]

 [[0.77718205 0.70763993 0.23427452]
  [0.2818742  0.30574892 0.21201595]
  [0.48404445 0.00781423 0.63235813]]

 [[0.29840981 0.7677918  0.15894887]
  [0.58410293 0.45519113 0.16931117]
  [0.68960746 0.29122218 0.63624302]]]


**Создать массив 5x5 со случайными значениями, найти минимум и максимум**

In [13]:
np_array = np.random.rand(5, 5)
print(np_array)
print(np.min(np_array))
print(np.max(np_array))

[[0.01480395 0.50645867 0.14025966 0.49831071 0.44693108]
 [0.03564982 0.94221778 0.40391151 0.30421919 0.09662227]
 [0.69970338 0.13995198 0.31046512 0.31979561 0.49151644]
 [0.78552371 0.31745023 0.88352019 0.28219646 0.31585674]
 [0.2508722  0.92242034 0.31172273 0.9263209  0.60076812]]
0.014803951809635785
0.9422177815071728


 **Создать случайный вектор размера 30 и найти среднее значение всех элементов**

In [14]:
np_array = np.random.rand(30)
print(np_array)
print(np.mean(np_array))

[0.07411747 0.39501187 0.16098023 0.06721181 0.05227701 0.1364103
 0.93674363 0.89506752 0.47857581 0.0655303  0.65191766 0.83463083
 0.27853123 0.6110777  0.49317869 0.97659532 0.05385316 0.34856639
 0.12056927 0.70113349 0.0644454  0.43553123 0.9965568  0.143391
 0.79488171 0.39232979 0.53193598 0.72053284 0.04701089 0.95151162]
0.4470035651048617


**Создать матрицу с 0 внутри, и 1 на границах**

In [15]:
np_array = np.ones((5, 5))
np_array[1:-1, 1:-1] = 0
print(np_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Выяснить результат следующих выражений  
    0 * np.nan  
	np.nan == np.nan  
	np.inf > np.nan  
	np.nan - np.nan**

In [16]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)

nan
False
False
nan


**Создать 5x5 матрицу с 1,2,3,4 под диагональю**

In [17]:
np_array = np.diag(np.arange(1, 5), k=-1)
print(np_array)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


**Создать 8x8 матрицу и заполнить её в шахматном порядке**

In [18]:
np_array = np.zeros((8, 8))
np_array[1::2, ::2] = 1
np_array[::2, 1::2] = 1
print(np_array)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?**

In [19]:
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


**Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile**

In [20]:
np_array = np.tile([[0, 1], [1, 0]], (4, 4))
print(np_array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
